# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: accountant.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'accountant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61\x63\x63ountant.proto\x12\naccountant\"(\n\x15SendAccountantRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"8\n\x16SendAccountantResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2l\n\x11\x41\x63\x63ountantService\x12W\n\x0eSendAccountant\x12!.accountant.SendAccountantRequest\x1a\".accountant.SendAccountantResponseB\"Z go-service/internal/grpc/gen;genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'accountant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z go-service/internal/grpc/gen;gen'
  _globals['_SENDACCOUNTANTREQUEST']._serialized_start=32
  _globals['_SENDACCOUNTANTREQUEST']._serialized_end=72
  _globals['_SENDACCOUNTANTRESPONSE']._serialized_start=74
  _globals['_SENDACCOUNTANTRESPONSE']._serialized_end=130
  _globals['_ACCOUNTANTSERVICE']._serialized_start=132
  _globals['_ACCOUNTANTSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
